### ISSUE TITLE
Sketch 2.1.1 FollowLight No Longer Works

### ISSUE THREAD

**Issue by starlord1980** [Freenove/Freenove_Basic_Starter_Kit_for_Raspberry_Pi#1]
Just been practicing the FollowLight sketch which fails to run and gives the error:
"When not using the PDE, size() can only be used inside settings()."

I had no idea what this means, but I persevered and I found the cause of the issue here:
https://github.com/processing/processing/issues/5759
It seems to be an issue with versions as I am using Processing 3.5.3.

I resolved it by removing size(640, 360) from the the code below

void setup() {  
  **size(640, 360); //display window size**  
  for (int i=0; i<10; i++) { //set led Pins to output mode  
    GPIO.pinMode(leds[i], GPIO.OUTPUT);  }  background

And adding void settings()

void settings() {
  **size(640, 360);  //display window size**
}

After that the code was able to run.

**Comment by DenzelChen** [comment]
Dear customer,
Thank you for your feedback.
I tested it again but I did not find the same error. Please send your result to support@freenove.com
Thank you.
Denzel
Freenove Support Team
